import { breadcrumbs, hero, linkButton } from '../templates/site.mjs';

const crumb = (label, path) => breadcrumbs([{ label: 'Inicio', path: '' }, { label, path }]);
const card = (title, text, path, label = 'Abrir herramienta') => `<article class="card"><h2>${title}</h2><p>${text}</p>${linkButton(path, label)}</article>`;
const field = (label, name, value, suffix) => `<label>${label}<span class="input-row"><input name="${name}" value="${value}" inputmode="decimal" required><span>${suffix}</span></span></label>`;
const error = '<div class="error" data-error role="alert" tabindex="-1" hidden></div>';

export const pages = [
  {
    path: '', h1: 'Elige cajas por medidas, no por intuición', title: 'EmbalaExacto: calculadoras de cajas y embalaje', description: 'Calcula cuántos objetos caben, la caja interior mínima y el peso volumétrico con fórmulas transparentes.',
    schema: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'EmbalaExacto', url: 'https://elvaropablo-oss.github.io/embala-exacto/', inLanguage: 'es-ES' },
    content: `${hero('Menos aire, menos dudas', 'Elige cajas por medidas, no por intuición', 'Compara las seis orientaciones rectangulares, calcula una caja interior compacta y estima el peso facturable con el divisor que te dé tu transportista.', `${linkButton('cuantas-caben/', 'Calcular cuántas caben')}${linkButton('caja-minima/', 'Diseñar caja mínima', true)}`)}
      <section class="section"><div class="section-heading"><p class="eyebrow">Un flujo conectado</p><h2>Del producto al bulto final</h2></div><div class="card-grid">${card('¿Cuántas caben?', 'Prueba automáticamente cada giro ortogonal y muestra la mejor retícula.', 'cuantas-caben/')}${card('Caja interior mínima', 'Busca una disposición compacta para una cantidad de objetos iguales.', 'caja-minima/')}${card('Peso volumétrico', 'Compara el peso real con el dimensional usando un divisor configurable.', 'peso-volumetrico/')}</div></section>
      <section class="section split"><div><p class="eyebrow">Resultado auditable</p><h2>Ves la orientación y las cuentas</h2><p>La herramienta muestra cuántas piezas van a lo largo, ancho y alto, cuánto espacio queda y qué porcentaje del volumen se ocupa. Así puedes comprobar el cálculo con una cinta métrica.</p></div><aside class="sample"><p>Ejemplo de disposición</p><strong>4 × 3 × 2 = 24 piezas</strong><p>Solo se consideran objetos rígidos e idénticos, colocados en filas rectas.</p></aside></section>`
  },
  {
    path: 'herramientas', h1: 'Herramientas para dimensionar embalajes', title: 'Herramientas de cajas y embalaje | EmbalaExacto', description: 'Calculadoras gratuitas para encajar objetos, dimensionar cajas y comparar peso real y volumétrico.',
    content: `${crumb('Herramientas', 'herramientas/')} ${hero('Directorio', 'Herramientas para dimensionar embalajes', 'Usa siempre dimensiones interiores para comprobar si algo cabe y exteriores para calcular peso volumétrico.')}
      <section class="section card-grid">${card('Cuántas caben', 'Compara las seis orientaciones de una pieza rectangular.', 'cuantas-caben/')}${card('Caja mínima', 'Obtén varias disposiciones compactas para piezas iguales.', 'caja-minima/')}${card('Peso volumétrico', 'Estima el peso dimensional y la base facturable.', 'peso-volumetrico/')}</section>`
  },
  {
    path: 'cuantas-caben', tool: true, h1: 'Calcula cuántos objetos caben en una caja', title: 'Cuántas cajas caben en otra caja | EmbalaExacto', description: 'Compara las seis orientaciones rectangulares y calcula cantidades, espacio restante y aprovechamiento.',
    content: `${crumb('Cuántas caben', 'cuantas-caben/')} ${hero('Seis orientaciones', 'Calcula cuántos objetos caben en una caja', 'Mide el hueco interior y una pieza ya protegida. La herramienta prueba todos los giros en ángulo recto.')}
      <section class="tool-layout"><form id="fit-form" class="tool-card"><fieldset><legend>Caja o hueco interior</legend>${field('Largo interior', 'containerLength', '60', 'cm')}${field('Ancho interior', 'containerWidth', '40', 'cm')}${field('Alto interior', 'containerHeight', '30', 'cm')}</fieldset><fieldset><legend>Objeto rectangular</legend>${field('Largo', 'itemLength', '20', 'cm')}${field('Ancho', 'itemWidth', '15', 'cm')}${field('Alto', 'itemHeight', '10', 'cm')}${field('Separación entre piezas', 'clearance', '0', 'cm')}</fieldset>${error}<button class="button" type="submit">Comparar orientaciones</button></form><section id="fit-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="section prose"><h2>Qué sí calcula</h2><p>Filas completas de objetos idénticos, rígidos y rectangulares. Una holgura se aplica entre piezas consecutivas, sin añadirla automáticamente contra las paredes.</p><h2>Qué no puede asegurar</h2><p>No resuelve formas irregulares, bolsas flexibles, piezas mezcladas, encaje diagonal, resistencia al apilado ni el cierre de la caja.</p></article>`
  },
  {
    path: 'caja-minima', tool: true, h1: 'Calcula una caja interior compacta', title: 'Calcular caja mínima para varios productos | EmbalaExacto', description: 'Busca dimensiones interiores compactas para una cantidad de objetos rectangulares iguales con separación y protección.',
    content: `${crumb('Caja mínima', 'caja-minima/')} ${hero('Planifica antes de comprar', 'Calcula una caja interior compacta', 'Indica las medidas de una pieza y cuántas quieres agrupar. Recibirás la opción de menor volumen y varias alternativas.')}
      <section class="tool-layout"><form id="minimum-form" class="tool-card"><fieldset><legend>Objeto y cantidad</legend>${field('Largo', 'itemLength', '20', 'cm')}${field('Ancho', 'itemWidth', '15', 'cm')}${field('Alto', 'itemHeight', '10', 'cm')}${field('Cantidad', 'quantity', '12', 'uds.')}</fieldset><fieldset><legend>Espacio adicional</legend>${field('Separación entre piezas', 'clearance', '0', 'cm')}${field('Protección contra cada pared', 'padding', '2', 'cm')}</fieldset>${error}<button class="button" type="submit">Buscar disposiciones</button></form><section id="minimum-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="section prose"><h2>Dimensiones interiores</h2><p>El resultado describe el hueco útil mínimo, no la medida exterior del cartón. Para convertirlo en una caja real debes sumar el grosor del material, tolerancias de fabricación y cierre.</p><h2>Cómo se elige la primera opción</h2><p>Se prioriza el menor volumen interior. En caso de empate se prefieren menos huecos sin usar y menor superficie total.</p></article>`
  },
  {
    path: 'peso-volumetrico', tool: true, h1: 'Compara peso real y peso volumétrico', title: 'Calculadora de peso volumétrico de envíos | EmbalaExacto', description: 'Calcula peso dimensional, peso facturable estimado y totales con divisor y redondeo configurables.',
    content: `${crumb('Peso volumétrico', 'peso-volumetrico/')} ${hero('Estimación transparente', 'Compara peso real y peso volumétrico', 'Usa las dimensiones exteriores del bulto cerrado y el divisor exacto de tu servicio. La herramienta no consulta tarifas.')}
      <section class="tool-layout"><form id="weight-form" class="tool-card"><fieldset><legend>Bulto exterior</legend>${field('Largo', 'length', '40', 'cm')}${field('Ancho', 'width', '30', 'cm')}${field('Alto', 'height', '20', 'cm')}${field('Peso real por bulto', 'actualWeight', '3', 'kg')}</fieldset><fieldset><legend>Regla de cálculo</legend>${field('Cantidad de bultos', 'quantity', '1', 'uds.')}<label>Divisor<select name="divisor"><option value="5000">5.000 cm³/kg</option><option value="6000">6.000 cm³/kg</option><option value="4000">4.000 cm³/kg</option><option value="custom">Otro</option></select></label>${field('Divisor personalizado', 'customDivisor', '5000', 'cm³/kg')}<label>Redondeo por bulto<select name="rounding"><option value="0">Sin redondeo</option><option value="0.5">Al siguiente 0,5 kg</option><option value="1">Al siguiente 1 kg</option></select></label></fieldset>${error}<button class="button" type="submit">Calcular pesos</button></form><section id="weight-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="section prose"><h2>Comprueba el divisor</h2><p>Los divisores, el redondeo, los mínimos y los recargos cambian según empresa, servicio y contrato. Copia el divisor de la tarifa que vayas a usar.</p><h2>No es un precio de envío</h2><p>El peso facturable estimado es el mayor entre peso real y volumétrico después del redondeo elegido. No incluye tarifas, zonas, combustible, medidas máximas ni otros recargos.</p></article>`
  },
  {
    path: 'guias/medir-caja', h1: 'Cómo medir una caja para que el cálculo sea útil', title: 'Cómo medir largo, ancho y alto de una caja | EmbalaExacto', description: 'Distingue medidas interiores y exteriores y evita errores al calcular encaje y peso volumétrico.',
    content: `${crumb('Cómo medir una caja', 'guias/medir-caja/')} ${hero('Interior para caber, exterior para enviar', 'Cómo medir una caja para que el cálculo sea útil', 'Usar la misma cifra para ambos fines puede hacer que una pieza no entre o que el peso volumétrico quede corto.')}
      <article class="section prose"><h2>Para comprobar si cabe</h2><ol><li>Mide el hueco interior entre paredes.</li><li>Resta solapas, separadores y refuerzos que invadan el espacio.</li><li>Mide el producto con su protección individual ya colocada.</li><li>Añade holgura si necesitas extraerlo con facilidad.</li></ol><h2>Para peso volumétrico</h2><p>Mide por fuera el bulto cerrado en sus puntos máximos. Incluye abombamientos, cinta, asas o salientes si el transportista los considera.</p>${linkButton('cuantas-caben/', 'Comprobar encaje')}</article>`
  },
  {
    path: 'metodologia', h1: 'Fórmulas y límites de EmbalaExacto', title: 'Metodología | EmbalaExacto', description: 'Consulta cómo se calculan orientaciones, cajas compactas, aprovechamiento y peso volumétrico.',
    content: `${crumb('Metodología', 'metodologia/')} ${hero('Cálculos que puedes revisar', 'Fórmulas y límites de EmbalaExacto', 'Cada resultado parte de prismas rectangulares alineados con los tres ejes.')}
      <article class="section prose"><h2>Encaje</h2><p>Para cada una de las seis permutaciones de largo, ancho y alto se calcula la parte entera de (hueco + separación) ÷ (pieza + separación) en cada eje. Las tres cantidades se multiplican.</p><h2>Caja compacta</h2><p>Se enumeran retículas enteras suficientes para la cantidad solicitada y todas las orientaciones. Se suman separaciones entre piezas y protección contra las dos paredes de cada eje.</p><h2>Peso volumétrico</h2><p>Peso dimensional = largo exterior × ancho exterior × alto exterior ÷ divisor. El peso facturable estimado es el mayor entre el real y el dimensional, con el redondeo seleccionado por bulto.</p><h2>Límite geométrico</h2><p>Una retícula recta es reproducible, pero no siempre es la solución matemática absoluta. Un encaje diagonal o alternado puede aprovechar mejor algunas formas.</p></article>`
  },
  {
    path: 'preguntas-frecuentes', h1: 'Preguntas frecuentes sobre cajas y embalaje', title: 'Preguntas frecuentes | EmbalaExacto', description: 'Respuestas sobre medidas, orientaciones, tolerancias y peso volumétrico.',
    content: `${crumb('Preguntas frecuentes', 'preguntas-frecuentes/')} ${hero('Antes de decidir', 'Preguntas frecuentes sobre cajas y embalaje', 'Las respuestas aclaran los supuestos que más cambian el resultado.')}
      <article class="section prose"><h2>¿Puedo usar milímetros?</h2><p>Sí. En los cálculos de encaje todas las longitudes pueden estar en cualquier unidad si usas la misma en todos los campos. El peso volumétrico está rotulado en centímetros porque el divisor se expresa en cm³/kg.</p><h2>¿La mejor opción siempre se puede montar?</h2><p>No. Comprueba acceso, solapas, resistencia y orden de colocación. La herramienta valida dimensiones, no el proceso físico.</p><h2>¿Por qué salen alternativas?</h2><p>Dos disposiciones pueden usar un volumen parecido, pero una encajar mejor en una estantería, pallet o límite de transporte.</p><h2>¿Guarda mis medidas?</h2><p>Solo se conserva localmente el último resultado en este navegador. No se envía a un servidor.</p></article>`
  },
  {
    path: 'sobre', h1: 'Sobre EmbalaExacto', title: 'Sobre el proyecto | EmbalaExacto', description: 'Propósito, alcance y límites de las herramientas de EmbalaExacto.',
    content: `${crumb('Sobre', 'sobre/')} ${hero('Una primera comprobación gratuita', 'Sobre EmbalaExacto', 'El proyecto convierte medidas de cajas en decisiones que pueden revisarse antes de comprar embalaje.')}
      <article class="section prose"><h2>Alcance</h2><p>La V1 trabaja con objetos idénticos y rectangulares. Está pensada para pequeñas tiendas, mudanzas, almacenaje y comparaciones iniciales de embalaje.</p><h2>Validación física</h2><p>Prueba una unidad real antes de comprar cajas en cantidad. El cartón, los refuerzos y la tolerancia de fabricación reducen el hueco útil.</p></article>`
  },
  {
    path: 'privacidad', h1: 'Privacidad', title: 'Privacidad | EmbalaExacto', description: 'Información sobre cálculo local y almacenamiento de EmbalaExacto.',
    content: `${crumb('Privacidad', 'privacidad/')} ${hero('Cálculos en tu navegador', 'Privacidad', 'Las dimensiones y los pesos se procesan en el dispositivo que estás usando.')}
      <article class="section prose"><h2>Datos introducidos</h2><p>Las medidas no se suben a un servidor. El último resultado puede guardarse en el almacenamiento local de este navegador para facilitar una comprobación posterior.</p><h2>Analítica</h2><p>Esta versión no instala Google Analytics ni servicios publicitarios.</p></article>`
  },
  { path: '404', output: '404.html', noindex: true, h1: 'Página no encontrada', title: 'Página no encontrada | EmbalaExacto', description: 'La página solicitada no existe.', content: `${hero('Error 404', 'Página no encontrada', 'La dirección puede contener un error o haber cambiado.', linkButton('', 'Volver al inicio'))}` }
];
